#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorI2CCustom)
#pragma config(Sensor, S3,     USback,         sensorSONAR)
#pragma config(Sensor, S4,     HTSMUX,         sensorLowSpeed)
#pragma config(Motor,  motorA,          arm,           tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     FrontRight,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     BackRight,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Flipper,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     BackLeft,      tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     FrontLeft,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    grabber,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    hood,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    USbackservo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    USfrontservo,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    trigger,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//!!!!!!!!!!!!!!!!!!!!!!!!ALWAYS CHANGE SENSOR S4 HTSMUX to sensorLowSpeed!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/*version 2/16/15
 *author: Eula
 *status: grab the goal from the ramp, line up, and go for the kickstand in all three positions
 */

#include "JoystickDriver.c"
#include "include\hitechnic-irseeker-v2.h"
#include "include\hitechnic-sensormux.h"
#include "include\lego-touch.h"
#include "include\lego-ultrasound.h"
#include "include\hitechnic-gyro.h"

//const tMUXSensor USback = msensor_S4_1;
const tMUXSensor USfront = msensor_S4_2;
const tMUXSensor TOUCHfront = msensor_S4_3;
const tMUXSensor TOUCHback = msensor_S4_4;

//everything is in centimeters
static float encoderScale=1120.0;
static float wheelRadius=((9.7)/2);
static float wheelCircumference=PI*2*wheelRadius;

//------------------------------nonmotor related basic stuffs--------------------------------------------------------------------------------------------
void initUS()
{
	//	servo[USfrontservo] = 220;
		servo[USbackservo] = 118;
}
void armOut(){
	time1[T3]=0;
	while((float)time1[T3]<2000){
		motor[arm] = -50;
	}
	motor[arm] = 0;
}

void armIn(){
	time1[T3]=0;
	while((float)time1[T3] < 2000){
		motor[arm] = 50;
	}
	motor[arm] = 0;
}

void grabberUp()
{
	servo[grabber] = 127;
}

void grabberDown()
{
	servo[grabber] = 60;
}

void hoodIn()
{
}

void hoodOut()
{
}
//----------------------------------plain movement stuffs---------------------------------------------------------------------------------
void resetEncoders(){
	nMotorEncoder[FrontLeft] = 0;
	nMotorEncoder[FrontRight] = 0;
	nMotorEncoder[BackLeft] = 0;
	nMotorEncoder[BackRight] = 0;
}

void Stop()
{
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
}


void mecJustMove(int speed, float degrees, float speedRotation)
{
	motor[FrontLeft] = speed * sinDegrees(degrees + 45) + speedRotation;
	motor[FrontRight] = speed * cosDegrees(degrees + 45) - speedRotation;
	motor[BackLeft] = speed * cosDegrees(degrees + 45) + speedRotation;
	motor[BackRight] = speed * sinDegrees(degrees + 45) -  speedRotation;
}


void mecMove(float speed, float degrees, float speedRotation, float distance)
{ //speed [-100,100], degrees [0, 360] to the right, speedRotation [-100,100], distance cm

	resetEncoders();
	float min = 0.0;
	if (cosDegrees(degrees) == 0.0 || sinDegrees(degrees) == 0.0)
	{
		min = 1.0;
	}
	else if (abs(1.0/cosDegrees(degrees))<= abs(1.0/sinDegrees(degrees)))
	{
		min = 1.0/cosDegrees(degrees);
	}
	else
	{
		min = 1.0/sinDegrees(degrees);
	}

	float scaled = abs(encoderScale* (distance * min / wheelCircumference));
	mecJustMove(speed, degrees, speedRotation);
	while((abs(nMotorEncoder[FrontLeft])<scaled) && (abs(nMotorEncoder[FrontRight])<scaled) && (abs(nMotorEncoder[BackLeft])< scaled) && (abs(nMotorEncoder[BackRight])< scaled))
	{}
	Stop();
	resetEncoders();
	wait1Msec(10);
}

void turnMecGyro(int speed, float degrees) {
	float delTime = 0;
	float curRate = 0;
	float currHeading = 0;
	Stop();
	wait1Msec(500);
	HTGYROstartCal(gyro);
	wait1Msec(500);
	//playSound(soundBeepBeep);
	mecJustMove (0, 0, speed);//+ = right   - = turn left
	while (abs(currHeading) < abs(degrees)) {
	time1[T1] = 0;
	curRate = HTGYROreadRot(gyro);
	if (abs(curRate) > 3) {
	currHeading += curRate * delTime; //Approximates the next heading by adding the rate*time.
	if (currHeading > 360) currHeading -= 360;
	else if (currHeading < -360) currHeading += 360;
	}
	wait1Msec(5);
	delTime = ((float)time1[T1]) / 1000; //set delta (zero first time around)
	}
	Stop();
}

void parallel()
{
	float difference=USreadDist(USfront) > SensorValue(USback)? 20:-20;//so that the sensors doesn't have to detect twice; to save batteries
	mecJustMove(0, 0, difference);
	while(abs(USreadDist(USfront)-SensorValue(USback))>5)
	{}
	Stop();
}

void readUSavg(float &frontS, float &backS)
{
	int f=0, b=0;
	for (int i=0; i<10; i++)
	{
		f+=USreadDist(USfront);
		b+=SensorValue(USback);
	}
	frontS=f/10.0;
	backS=b/10.0;
}

void moveTillUS(float speed, float degrees, float speedRotation, float threshold, bool till)//if till = true, move until sees something; if till = false, move until not seeing something
{
   mecJustMove(speed, degrees, speedRotation);
   if (till){
   	while ((USreadDist(USfront) > threshold)){}}
   else{
    	while ((USreadDist(USfront)) < threshold || (SensorValue(USback) < threshold)){}}//should be ||, so stop when none of them is in the threshold
		Stop();
}

//===================================================================================================================================
task main()
{
	int delay=0;
	while(nNxtButtonPressed!=3){
		if(nNxtButtonPressed==1) delay++;
		else if(nNxtButtonPressed==2 && delay>0) delay--;
		nxtDisplayCenteredTextLine(2, "%d", delay);
		wait1Msec(200);
	}
	waitForStart();
	nxtDisplayCenteredTextLine(2, "%d", delay);
	wait1Msec(1000*delay);

	eraseDisplay();

	//*******Intialization***************************************
	hoodIn();
	grabberUp();
	time1[T2]=0;
	int Cposition;
	//********Approach goal*********************
	mecMove(50.0, 0, 0, 170.0);//**1st length: move down the ramp
  mecMove(100.0, -90.0, 0, 64.0);//2nd length: move to the left facing the rolling goal
	mecMove(50.0, 0.0, 0.0, 120.0);//**3rd length: approach the rolling goal and ramp into the wall

	//*********Grab goal************************
	wait1Msec(250);
	grabberDown();
	wait1Msec(500);
	mecMove(100.0, 180, 0 , 5.0);//**back up 5 cm
	wait1Msec(100);
	hoodOut();

//***********Return to PZ**********
	motor[Flipper] = -100.0; //start thrower motor
	mecMove(-100.0, 0, 0, 360.0);//move back to ramp side and ramp into the wall to align
	mecMove(50.0, 0, 0, 5);//move away from wall
//	mecMove(100.0, -90, 0, 100-SensorValue[USback]);
	mecMove(100.0, -90, 0, 80);//first hard code some stuffs just in case
	moveTillUS(100.0, -90, 0, 110, false);
	turnMecGyro(-50, 90);
	wait1Msec(10);
	grabberUp();
	motor[Flipper] = 0;//stop flipper
	hoodIn();
	wait1Msec(200);
	mecMove(-40, 0, 0, 10);//drop and back out from the goal
	mecMove(90, -90, 0, 15); //so it is lined up with the wall as the set up in the centergoal program -->to read those values in the same way

	//*********Kickstand***********************
		float frontS=0, backS=0;
		readUSavg(frontS, backS);

	if (frontS > 250 && backS > 250) {
		Cposition = 2;
		DisplayCenteredTextLine(2, "%d", Cposition);
		playSound(soundDownwardTones);
		}
	else if(frontS > 103 && frontS < 113){//the other value is... doesn't matter
		Cposition = 3;
		DisplayCenteredTextLine(2, "%d", Cposition);
		playSound(soundUpwardTones);
		}
		else{ //values between 128-134, but don't need it really
			Cposition = 1;
			DisplayCenteredTextLine(2, "%d", Cposition);
			playSound(soundBeepBeep);
		}

switch (Cposition)
	{
		case 1:{
			mecMove(40, 90, 0, 40);//to move away from the PZ(the goal)
//			mecMove(100.0, -90.0, 0, 60);//turn counter-clockwise 90 degrees, flipper side facing the opponent's side and kickstand arm facing kickstand
			mecMove(-90, 0, 0, 60);//move toward opponent's side, grabber forward, kickstand arm facing centergoal
			armOut();
			mecMove(-90, 0, 0, 90);//go for the kickstand
		};
		break;
		case 2:{
			mecMove(70, 90, 0, 120);//move toward the centergoal
			turnMecGyro(60, 135);//turn clockwise 135 degree and arm toward the kickstand
			armOut();
			mecMove(-90, 0, 0, 90);//go for the kickstand
		};
		break;
		case 3:{
			mecMove(-90, 0, 0, 60);//line up with the kickstand
			turnMecGyro(40, 270);//arm facing kickstand
			mecMove(-90, 0, 0, 180);//go for the kickstand
		}
		break;
	}
		mecMove(90, 90, 0, 20);//optional, move sideway in case the kickstand is not down

//-----------------------------------------------------------------------------
}
