#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     gyro,           sensorAnalogInactive)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     thrower,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    grabber1,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    grabber2,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "drivers/hitechnic-gyro.h"
void resetEncoders(){
	nMotorEncoder[motorRight] = 0;
	nMotorEncoder[motorLeft] = 0;
}

void turn(float speed){//+ = turn right     - = turn left
	motor[motorLeft] = speed;
	motor[motorRight] = 0-speed;
}

void turnWithGyro(int speed, float degrees) {
	float delTime = 0;
	float curRate = 0;
	float currHeading = 0;
	motor [motorLeft]=0;
	motor [motorRight]=0;
	wait1Msec(300);
  HTGYROstartCal(gyro);
 	wait1Msec(300);
 	PlaySound(soundBeepBeep);
 	turn (speed);//+ = right   - = turn left
  while (abs(currHeading) < abs(degrees)) {
    time1[T1] = 0;
    curRate = HTGYROreadRot(gyro);
    if (abs(curRate) > 3) {
      currHeading += curRate * delTime; //Approximates the next heading by adding the rate*time.
      if (currHeading > 360) currHeading -= 360;
      else if (currHeading < -360) currHeading += 360;
    }
    wait1Msec(5);
    delTime = ((float)time1[T1]) / 1000; //set delta (zero first time around)
  }
  turn(0);
}

//everything is in centimeters
static float encoderScale=1440.0;
static float wheelRadius=((9.7)/2);
static float wheelCircumference=PI*2*wheelRadius;
//static float AngleRatio = ? //used as angle(in degree) * AngleRatio
task main()
{
	int delay=0;
	while(nNxtButtonPressed!=3){
		if(nNxtButtonPressed==1) delay++;
		else if(nNxtButtonPressed==2 && delay>0) delay--;
		nxtDisplayCenteredTextLine(2, "%d", delay);
		wait1Msec(200);
	}
	waitForStart();
	nxtDisplayCenteredTextLine(2, "%d", delay);
	wait1Msec(1000*delay);
	turnWithGyro(100, 3.2);// turn in parking zone

	resetEncoders();
	motor[motorLeft] = 100;
	motor[motorRight] = 100;
	while(nMotorEncoder[motorLeft] <= encoderScale * (132.0 / wheelCircumference) )
	{

	}
	int pos1 = 0;
	int pos2 = 255;
	servo[grabber1]=pos2;//grabbers and pos switched
	servo[grabber2]=pos1;
	motor[motorLeft] = 0;
	motor[motorRight] = 0;

	turnWithGyro(-100, 4.8);//turn towards goal

	resetEncoders();
	motor[motorLeft] = 100;
	motor[motorRight] = 100;
	while(nMotorEncoder[motorLeft] <= encoderScale * (128.0 / wheelCircumference) )	//approach goal
	{
	}
	motor[motorLeft] = 0;
	motor[motorRight] = 0;
	wait1Msec(10);

	resetEncoders();
	motor[motorLeft] = 60;
	motor[motorRight] = 60;
	while(nMotorEncoder[motorLeft] <= encoderScale * (28.0 / wheelCircumference) )	//slowly approach goal
	{
	}
	motor[motorLeft] = 0;
	motor[motorRight] = 0;
	wait1Msec(10);

	resetEncoders();

	wait10Msec(50);
	pos1=255;
	pos2=0;//grab down
	servo[grabber1]=pos2;
	servo[grabber2]=pos1;
	wait10Msec(50);

	resetEncoders();
	motor[motorLeft] = -100;
	motor[motorRight] = -100;
	while(abs(nMotorEncoder[motorLeft]) <= encoderScale * 2 * (5.0 / wheelCircumference) )//move backwards to get robot off goal base
	{
	}

	turnWithGyro(-100,173.0);//turn back to parking zone


	resetEncoders();
	motor[motorLeft] = 60.0;
	motor[motorRight] = 60.0;
	motor[thrower] = -100.0; //start thrower motor

	while(abs(nMotorEncoder[motorLeft]) <= encoderScale * 2 * (80.0 / wheelCircumference) ) // move forward 80 cm
	{
	}
	resetEncoders();


	turnWithGyro(100, 11.0);//turn towards parking zone

	resetEncoders();
	motor[motorLeft] = 100;
	motor[motorRight] = 100;
	while(nMotorEncoder[motorLeft] <= encoderScale * (100.0 / wheelCircumference) )	//approach parking zone
	{
	}
	motor[motorLeft] = 0;
	motor[motorRight] = 0;
	wait1Msec(10);

	motor[motorLeft] = 0;
	motor[motorRight] = 0;
	wait1Msec(500);
	pos1 = 0;
	pos2 = 255;
	//servo[grabber1]=pos2;
	//servo[grabber2]=pos1;
	wait1Msec(10000);

}
