#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     gyro,           sensorAnalogInactive)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     thrower,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    grabber1,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    grabber2,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "include\hitechnic-gyro.h"
void resetEncoders(){
	nMotorEncoder[motorRight] = 0;
	nMotorEncoder[motorLeft] = 0;
}

void turn(float speed){//+ = turn right     - = turn left
	motor[motorLeft] = speed;
	motor[motorRight] = 0-speed;
}

void turnWithGyro(int speed, float degrees) {
	float delTime = 0;
	float curRate = 0;
	float currHeading = 0;
	motor [motorLeft]=0;
	motor [motorRight]=0;
	wait1Msec(500);
  HTGYROstartCal(gyro);
 	wait1Msec(500);
 	PlaySound(soundBeepBeep);
 	turn (speed);//+ = right   - = turn left
  while (abs(currHeading) < abs(degrees)) {
    time1[T1] = 0;
    curRate = HTGYROreadRot(gyro);
    if (abs(curRate) > 3) {
      currHeading += curRate * delTime; //Approximates the next heading by adding the rate*time.
      if (currHeading > 360) currHeading -= 360;
      else if (currHeading < -360) currHeading += 360;
    }
    wait1Msec(5);
    delTime = ((float)time1[T1]) / 1000; //set delta (zero first time around)
  }
  turn(0);
}

//everything is in centimeters
static float encoderScale=1440.0;
static float wheelRadius=((9.7)/2);
static float wheelCircumference=PI*2*wheelRadius;
//static float AngleRatio = ? //used as angle(in degree) * AngleRatio
task main()
{
	int delay=0;
	while(nNxtButtonPressed!=3){
		if(nNxtButtonPressed==1) delay++;
		else if(nNxtButtonPressed==2 && delay>0) delay--;
		nxtDisplayCenteredTextLine(2, "%d", delay);
		wait1Msec(200);
	}
	waitForStart();
	nxtDisplayCenteredTextLine(2, "%d", delay);
	wait1Msec(1000*delay);

	int pos1 = 0;
 	int pos2 = 255;
	servo[grabber1]=pos2;//they are switched
	servo[grabber2]=pos1;

	resetEncoders();
	motor[motorLeft] = 50;
	motor[motorRight] = 50;

	while(nMotorEncoder[motorLeft] <= encoderScale * (167.0 / wheelCircumference) )//169
	{
	}
	motor[motorLeft] = 0;
	motor[motorRight] = 0;

	wait1Msec(10);

	turnWithGyro(-100.0, 8.5);

	resetEncoders();
	motor[motorLeft] = 50;
	motor[motorRight] = 50;
	while(abs(nMotorEncoder[motorLeft]) <= encoderScale * 2 * (56.0 / wheelCircumference) )//move forward 55 cm, approach goal
	{
	//	motor[motorLeft] = -100*( (encoderScale * (56.0 / wheelCircumference))- nMotorEncoder[motorLeft])/ encoderScale * 2 * (56.0 / wheelCircumference) );
	//	motor[motorRight] = -100*(nMotorEncoder[motorRight]-(encoderScale * (56.0 / wheelCircumference)));
	}

	motor[motorLeft] = 0;//stop robot
	motor[motorRight] = 0;
	resetEncoders();

	wait10Msec(50);
	pos1=255;
	pos2=0;//grabber completely down
	servo[grabber1]=pos2;
	servo[grabber2]=pos1;
	wait10Msec(50);

	resetEncoders();
	motor[motorLeft] = -50;
	motor[motorRight] = -50;
	while(abs(nMotorEncoder[motorLeft]) <= encoderScale * 2 * (5.0 / wheelCircumference) )//move backwards to get robot off goal base
	{
	}
	turnWithGyro(-100.0,135.0);//turn 125 degrees around
	resetEncoders();
	motor[motorLeft] = 100.0;
	motor[motorRight] = 100.0;

	motor[thrower] = -100.0; //start thrower motor

	while(abs(nMotorEncoder[motorLeft]) <= encoderScale * 2 * (90.0 / wheelCircumference) ) // move forward 281 cm
	{
	}
	resetEncoders();

	turnWithGyro(100.0,15.0);//turn 125 degrees around
	resetEncoders();
	motor[motorLeft] = 100.0;
	motor[motorRight] = 100.0;

	while(abs(nMotorEncoder[motorLeft]) <= encoderScale * 2 * (40.0 / wheelCircumference) )
	{
	}
	resetEncoders();

	motor[motorLeft] = 0;
	motor[motorRight] = 0;
	wait1Msec(500);
	pos1 = 0;
	pos2 = 255;
	//servo[grabber1]=pos2;
	//servo[grabber2]=pos1;

	wait1Msec(10000);

}
