
#pragma config(Sensor, S3,     HTIRS2,         sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h"

task main()
{
  // Create struct to hold sensor data
  tHTIRS2 irSeeker;

  // Initialise and configure struct and port
  initSensor(&irSeeker, S3);

  if (true)
  {
  	int position;
  	float reading1;
  	float reading2;

  	tHTIRS2 irSeeker;
  	initSensor(&irSeeker, S3);
  	irSeeker.mode = DSP_1200;

  	readSensor(&irSeeker);
  	reading1 = irSeeker.acDirection;

  	playSound(soundBeepBeep);
  	displayTextLine(1, "D:%4d", reading1);
  	wait1Msec(5000);

  	readSensor(&irSeeker);
  	reading2 = irSeeker.acDirection;
  	playSound(soundFastUpwardTones);
  	displayTextLine(2, "K: %d", reading2);
  	displayTextLine(3, "1: %d", reading1);
  	displayTextLine(4, "2: %d", reading2);
  	wait1Msec(5000);
  	if (reading1 == 5 && reading2 == 5)
  	{
  		playSound(soundBeepBeep);
  		wait1Msec(3000);
  	 	position = 1;
  	 	displayTextLine(5, "pos: %d", position);
  		wait1Msec(5000);
  	}
    else if (reading1 == 5 && (reading2 == 4 || reading2 == 3))
		{
			playSound(soundLowBuzz);
  		wait1Msec(3000);
  	 	position = 3;
  	 	displayTextLine(5, "pos: %d", position);
  		wait1Msec(5000);
		}
   else
 		{
 			playSound(soundFastUpwardTones);
  		wait1Msec(3000);
  	 	position = 2;
  	 	displayTextLine(5, "pos: %d", position);
  		wait1Msec(5000);
 		}

   switch(position)
   {
     case 1: playSound(soundBeepBeep);
     wait1Msec(2000);
     displayTextLine(1, "at: %d", position);
     break;
     case 2: playSound(soundFastUpwardTones);
     wait1Msec(2000);
     displayTextLine(1, "at: %d", position);
     break;
     case 3: playSound(soundLowBuzz);
     wait1Msec(2000);
     displayTextLine(1, "at: %d", position);
     break;
   }
  }

}
