#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     FrontLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     BackLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     BackRight,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     FrontRight,    tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//version 12/16/14   test waiting time changed(Btn 5&7)   hood angle changed 100 --> 110

#include "JoystickDriver.c"
task main()
{

	waitForStart();
    while(true){
	   getJoystickSettings(joystick);

	   if(abs(joystick.joy1_y1)<10)
	   {
	    joystick.joy1_y1=0;
	   }
	   if(abs(joystick.joy1_y2)<10)
	   {
	    joystick.joy1_y2=0;
	   }
	   if(abs(joystick.joy1_x1)<10)
	   {
	    joystick.joy1_x1=0;
	   }
	   if(abs(joystick.joy1_x2)<10)
	   {
	    joystick.joy1_x2=0
	   }
	 /*  FrontLeft = Ch3 + Ch1 + Ch4
RearLeft = Ch3 + Ch1 - Ch4
FrontRight = Ch3 - Ch1 - Ch4
RearRight = Ch3 - Ch1 + Ch4

Where:*/
int Rot = joystick.joy1_x2;//Right joystick X-axis
int Fwd = joystick.joy1_y1;//-Left joystick Y-axis
int Side= joystick.joy1_x1;// Left joystick X-axis

	    motor[FrontLeft] = 100.0/384 * (-Fwd + Rot - Side);
			motor[FrontRight] = 100.0/384 * (-Fwd - Rot + Side);
			motor[BackLeft] = 100.0/384* (-Fwd + Rot + Side);
			motor[BackRight] = 100.0/384 * (-Fwd - Rot - Side);

     wait1Msec(10);
  }
}
