#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorAnalogInactive)
#pragma config(Motor,  mtr_S1_C1_1,     FrontLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     FrontRight,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     BackLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     BackRight,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     thrower,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    grabber1,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    grabber2,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    hood,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//version 12/17/14 total time function added

#include "JoystickDriver.c"
#include "include\hitechnic-gyro.h"

//everything is in centimeters
static float encoderScale=1440.0;
static float wheelRadius=((9.7)/2);
static float wheelCircumference=PI*2*wheelRadius;
//static float AngleRatio = ? //used as angle(in degree) * AngleRatio

void resetEncoders(){
	nMotorEncoder[FrontLeft] = 0;
	nMotorEncoder[FrontRight] = 0;
	nMotorEncoder[BackLeft] = 0;
	nMotorEncoder[BackRight] = 0;
}

void mecMove(float speed, float degrees, float speedRotation, float distance){ //speed [-1,1], degrees [0, 360], speedRotation [-1,1]
		playSound(soundBeepBeep);
		resetEncoders();
		float min = 0.0;
		if (abs(1/cosDegrees(degrees))<= abs(1/sinDegrees(degrees)))
			{
				min = 1/cosDegrees(degrees);
			}
		else
			{
				min = 1/sinDegrees(degrees);
			}
		float scaled = encoderScale* distance * min / wheelCircumference;
		//bool run = (nMotorEncoder[FrontLeft]<scaled) && (nMotorEncoder[FrontRight]<scaled) && (nMotorEncoder[BackLeft]< scaled) && (nMotorEncoder[BackRight]< scaled);
		bool run = true;
		motor[FrontLeft] = speed * sinDegrees(degrees + 45) + speedRotation;
		motor[FrontRight] = speed * cosDegrees(degrees + 45) - speedRotation;
		motor[BackLeft] = speed * cosDegrees(degrees + 45) + speedRotation;
		motor[BackRight] = speed * sinDegrees(degrees + 45) -  speedRotation;
		while(run)
		{
  	}
		motor[BackLeft] = 0;
		motor[BackRight] = 0;
		motor[FrontLeft] = 0;
		motor[FrontRight] = 0;
		resetEncoders();
}

void parallel(){

}



task main()
{
	playSound(soundBeepBeep);
	int delay=0;
	while(nNxtButtonPressed!=3){
		if(nNxtButtonPressed==1) delay++;
		else if(nNxtButtonPressed==2 && delay>0) delay--;
		nxtDisplayCenteredTextLine(2, "%d", delay);
		wait1Msec(200);
	}
	waitForStart();
	nxtDisplayCenteredTextLine(2, "%d", delay);
	wait1Msec(1000*delay);
	mecMove(1, 0, 1, 10);
	mecMove(1, 90, 1, 10);
	mecMove(1, 45, 1, 10);


	/******move to the right side of PZ**********************
	move(100.0, 130.0);//**length: move back
	turnWithGyro(100, 50.0);//turn towards parking zone
	move(100, 120.0);//**length: move right to the right side of the PZ
	turnWithGyro(-100, 60.0);//turn towards right side of parking zone
	move(100,20.0);//**length: move into the PZ
	**********************************************************/
	/*float totaltime = (float)Time1[T2]/1000.0;
	wait1Msec((30.0-totaltime-(float)delay)*1000.0);
	pos3 = 10;
	servo[hood] = pos3;//to prevent the hood from falling onto the tube when the program stops
	wait1Msec(500);
	*/

}
