#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     thrower,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    grabber1,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    grabber2,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
void resetEncoders(){
	nMotorEncoder[motorRight] = 0;
	nMotorEncoder[motorLeft] = 0;
}
//everything is in centimeters
static float encoderScale=1440.0;
static float wheelRadius=((9.7)/2);
static float wheelCircumference=PI*2*wheelRadius;
//static float AngleRatio = ? //used as angle(in degree) * AngleRatio
task main()
{
	int pos1 = 0;
	int pos2 = 255;
	servo[grabber1]=pos2;//they are switched
	servo[grabber2]=pos1;

	resetEncoders();
	motor[motorLeft] = 100;
	motor[motorRight] = 100;

	while(nMotorEncoder[motorLeft] <= encoderScale * (169.0 / wheelCircumference) )
	{
	}
	motor[motorLeft] = 0;
	motor[motorRight] = 0;
	wait10Msec(50);

	/*		if(motor[motorLeft]==0){
	for(int i=0;i<10;i++){
	//		while(pos1<=255 && pos2>=0){
	pos1+=5;
	pos2-=5;
	if (pos1>=255) pos1=255;
	if(pos2<=0) pos2=0;
	servo[grabber1] = (pos2);
	servo[grabber2] = (pos1);
	}
	}*/
	resetEncoders();
	motor[motorLeft] = -100;
	motor[motorRight] = 100;

	while(abs(nMotorEncoder[motorLeft]) <= encoderScale * 2 * (1.55 / wheelCircumference) ) // rotate towards goal
	{
	}
	resetEncoders();
	motor[motorLeft] = 65;
	motor[motorRight] = 65;


	while(abs(nMotorEncoder[motorLeft]) <= encoderScale * 2 * (51.0 / wheelCircumference) )//move forward 46.8 cm, approach goal
	{
	}

	motor[motorLeft] = 0;//stop robot
	motor[motorRight] = 0;
	resetEncoders();

	wait10Msec(50);
	pos1=100;
	pos2=155;//grabber not completely down
	servo[grabber1]=pos2;
	servo[grabber2]=pos1;
	wait10Msec(50);

	resetEncoders();
	motor[motorLeft] = -100;
	motor[motorRight] = -100;
	while(abs(nMotorEncoder[motorLeft]) <= encoderScale * 2 * (5.0 / wheelCircumference) )//move backwards to get robot off goal base
	{
	}
	resetEncoders();
	motor[motorLeft] = -100;
	motor[motorRight] = 100;

	while(abs(nMotorEncoder[motorLeft]) <= encoderScale * 2 * (48.0 / wheelCircumference) ) // rotate counterclockwise 139.5 degree
	{
	}
	resetEncoders();
	motor[motorLeft] = 70.0;
	motor[motorRight] = 70.0;
	motor[thrower] = -100.0; //start thrower motor

	while(abs(nMotorEncoder[motorLeft]) <= encoderScale * 2 * (110.0 / wheelCircumference) ) // move forward 281 cm
	{
	}
	resetEncoders();

	motor[motorLeft] = 0;
	motor[motorRight] = 0;
	// motor[thrower] = -100.0; //start thrower motor
	wait1Msec(500);
	pos1 = 0;
	pos2 = 255;
	servo[grabber1]=pos2;
	servo[grabber2]=pos1;
	wait1Msec(1000000);
	//	motor[thrower] = -100.0; //start thrower motor


	/*		motor[motorLeft] = -100;
	motor[motorRight] = -100;
	while(abs(nMotorEncoder[motorLeft]) <= encoderScale * 2 * (10.0 / wheelCircumference) ) // move forward 281 cm
	{
	}

	motor[motorLeft] = 0;
	motor[motorRight] = 0;
	resetEncoders();*///this part mess up the angles...... eh

}
