#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    grabber1,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    grabber2,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
void resetEncoders(){
		nMotorEncoder[motorRight] = 0;
		nMotorEncoder[motorLeft] = 0;
		}
//everything is in centimeters
static float encoderScale=1440.0;
static float wheelRadius=((9.7)/2);
static float wheelCircumference=PI*2*wheelRadius;
task main()
{
	int pos1 = 0;
	int pos2 = 255;
	servo[grabber1]=pos2;//they are swtiched
	servo[grabber2]=pos1;

  	resetEncoders();
  	motor[motorLeft] = 100;
  	motor[motorRight] = 100;

		while(nMotorEncoder[motorLeft] <= encoderScale * (250.0 / wheelCircumference) )
		{
		}
		motor[motorLeft] = 0;
		motor[motorRight] = 0;
		wait10Msec(150);
		pos1=100;
		pos2=155;
		servo[grabber1]=pos2;
		servo[grabber2]=pos1;
		wait10Msec(150);
/*		if(motor[motorLeft]==0){
			for(int i=0;i<10;i++){
		//		while(pos1<=255 && pos2>=0){
			 	pos1+=5;
			 	pos2-=5;
			 	if (pos1>=255) pos1=255;
			 	if(pos2<=0) pos2=0;
	     	servo[grabber1] = (pos2);
	     	servo[grabber2] = (pos1);
			}
		}*/
	  resetEncoders();
  	motor[motorLeft] = -100;
  	motor[motorRight] = 100;

		while(abs(nMotorEncoder[motorLeft]) <= encoderScale * 2 * (59.8 / wheelCircumference) ) // rotate counterclockwise 150 degree
		{
		}
		motor[motorLeft] = 100;
		motor[motorRight] = 100;
		
		while(abs(nMotorEncoder[motorLeft]) <= encoderScale * 2 * (250.0 / wheelCircumference) )//move forward 250 cm
		{
		}
		
		motor[motorLeft] = 0;
		motor[motorRight] = 0;
		
	 pos1 = 0;
	 pos2 = 255;
	servo[grabber1]=pos2;
	servo[grabber2]=pos1;
}
