#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    grabber1,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    grabber2,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
void resetEncoders(){
		nMotorEncoder[motorRight] = 0;
		nMotorEncoder[motorLeft] = 0;
		}

static float encoderScale=1440.0;
static float wheelRadius=5.0;
static float wheelCircumference=PI*2*wheelRadius;
task main()
{
  	resetEncoders();
  	motor[motorLeft] = 100;
  	motor[motorRight] = 100;

		while(nMotorEncoder[motorLeft] <= encoderScale * (100.0 / wheelCircumference) )
		{
		}
		motor[motorLeft] = 0;
		motor[motorRight] = 0;
}
