#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorI2CCustom)
#pragma config(Sensor, S3,     irSeeker,       sensorI2CCustom)
#pragma config(Sensor, S4,     HTSMUX,         sensorLowSpeed)
#pragma config(Motor,  motorA,          arm,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     BackLeft,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     FrontLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     thrower,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     FrontRight,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     BackRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    grabber1,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    grabber2,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    hood,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    liftRelease,          tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//version 2/11/15   Status:
//different function = different task

#include "JoystickDriver.c"
#include "include\hitechnic-irseeker-v2.h"
#include "include\hitechnic-sensormux.h"
#include "include\lego-touch.h"
#include "include\lego-ultrasound.h"
#include "include\hitechnic-gyro.h"

//const tMUXSensor TOUCHFront = msensor_S4_3;
//const tMUXSensor TOUCHBack = msensor_S4_4;

	static float encoderScale=1120.0;
	static int pos1 = 255;
	static int pos2 = 0;
	static int pos4 = 50;
	static int frontback = 1;

//===========================Thrower====================================
task throwerStop()
{
	motor[thrower] = 0;
}

task throwerForward()
{
	motor[thrower] = -100;
}

task throwerReverse()
{
	motor[thrower] = 50;
}
//==========================Grabber==============================================
task grabberUp()
{
	pos1+=5;
	pos2-=5;
	if (pos1 >= 255) pos1=255;
	if(pos2<=0) pos2=0;
	servo[grabber1] = (pos1);
	servo[grabber2] = (pos2);
}

task grabberDown()
{
	pos1-=5;
	pos2+=5;
	if (pos1 <= 0) pos1=0;
	if(pos2>=255) pos2=255;
	servo[grabber1] = (pos1);
	servo[grabber2] = (pos2);
}

//=========================Kickstand Arm======================================================
task kArmOut()
{
	motor[arm] = 50;
	while(joy1Btn(5))
	{
		wait1Msec(10);
	}
	motor[arm]=0;
}

task kArmIn()
{
	motor[arm] = -50;
	while(joy1Btn(7))
	{
		wait1Msec(10);
	}
	motor[arm]=0;
}

//=========================Lift===================================================================
task liftUp()
{
	nMotorEncoder[Lift]=0;
	motor[Lift]=-30;
	//servo[liftRelease] = 143; //up ratio of -30/(143-127) =-1.875
	while(abs(nMotorEncoder[Lift])<encoderScale)
	{
		wait1Msec(10);
	}
	motor[Lift]=0;
	//servo[liftRelease] = 127;
}

task liftDown()
{
	nMotorEncoder[Lift]=0;
	motor[Lift]=25;
	//servo[liftRelease] = 60;
	while(abs(nMotorEncoder[Lift])<encoderScale)
	{
		wait1Msec(10);
	}
	motor[Lift]=0;
	//servo[liftRelease] = 127;
}

//========================Hood===========================================================
task hoodOut()
{
	pos4 = 107;
	wait1Msec(1);
	servo[hood] = pos4;
}

task hoodIn()
{
	pos4 = 50;
	wait1Msec(1);
	servo[hood] = pos4;
}

//=========================Change Direction=============================================
task grabberFront()
{
	frontback = -1;
}

task flipperFront()
{
	frontback = 1;
}

//--------------------------------------------------------------------------------------
task main()
{
	servo[grabber1]=pos1;
	servo[grabber2]=pos2;
	servo[hood] = pos4;
	//servo[liftRelease] = 127;
	waitForStart();

	while(true){
//===================================================driving stuffs======================================
		getJoystickSettings(joystick);
		if(abs(joystick.joy1_y1)<10)
		{
			joystick.joy1_y1=0;
		}
		if(abs(joystick.joy1_y2)<10)
		{
			joystick.joy1_y2=0;
		}
		if(abs(joystick.joy1_x1)<10)
		{
			joystick.joy1_x1=0;
		}
		if(abs(joystick.joy1_x2)<10)
		{
			joystick.joy1_x2=0;
		}

		if(frontback==1){
			motor[FrontLeft] = (-100.0/256 * (-joystick.joy1_y1 - (joystick.joy1_x1 + joystick.joy1_x2) / 2));
			motor[BackLeft] = (-100.0/256 * (-joystick.joy1_y1 + (joystick.joy1_x1 + joystick.joy1_x2) / 2));
			motor[FrontRight] =  (-100.0/256 * (-joystick.joy1_y2 + (joystick.joy1_x1 + joystick.joy1_x2) / 2));
			motor[BackRight] = (-100.0/256 * (-joystick.joy1_y2 - (joystick.joy1_x1 + joystick.joy1_x2) / 2));
		}

		else{
			motor[FrontRight] = frontback * (-100.0/256 * (-joystick.joy1_y1 - frontback * (joystick.joy1_x1 + joystick.joy1_x2) / 2));
			motor[BackRight] = frontback * (-100.0/256 * (-joystick.joy1_y1 + frontback * (joystick.joy1_x1 + joystick.joy1_x2) / 2));
			motor[FrontLeft] = frontback * (-100.0/256 * (-joystick.joy1_y2 + frontback * (joystick.joy1_x1 + joystick.joy1_x2) / 2));
			motor[BackLeft] = frontback * (-100.0/256 * (-joystick.joy1_y2 - frontback * (joystick.joy1_x1 + joystick.joy1_x2) / 2));
		}
//=================================================Thrower======================================================
		if(joy1Btn(1))	{startTask(throwerStop);}
		if(joy1Btn(6))	{startTask(throwerForward);}
		if(joy1Btn(8))	{startTask(throwerReverse);}
//=================================================kickstand arm====================================================
		if (joy1Btn(5))	{startTask(kArmOut);}
		if (joy1Btn(7))	{startTask(kArmIn);}
//=================================================change direction====================================================
		if (joy1Btn(2))	{startTask(grabberFront);}
		if (joy1Btn(4))	{startTask(flipperFront);}
//-------------------------------------------------Joystick 2 ------------------------------------------------------
//==================================================Grabber=======================================================
		if(joy2Btn(4))	{startTask(grabberUp);}
		if(joy2Btn(2))	{startTask(grabberDown);}
//==================================================Hood==============================================================
		if(joy2Btn(5))	{startTask(hoodOut);}
		if(joy2Btn(7))	{startTask(hoodIn);}
//==================================================Lift======================================================================================
		if(joy2Btn(6))	{startTask(liftDown);}
		if(joy2Btn(8))	{startTask(liftUp);}

		wait1Msec(10);
		/*	if(joy2Btn(6)){
		servo[liftRelease] = 150;
		while(joy2Btn(6))
		{
		}
		servo[liftRelease] = 127;
		}

		if(joy2Btn(8)){ //tighten up the servo
		servo[liftRelease] = 90;
		while(joy2Btn(8))
		{
		}
		servo[liftRelease] = 127;
		}*/
	}
}
